spring.application.name=Prospera

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=prospera
spring.datasource.username=prospera
spring.datasource.password=prospera


# Specify the JDBC driver for PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings for JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port = 8088
spring.jpa.properties.hibernate.default_schema=prospera
spring.jpa.properties.hibernate.physical_naming_strategy=com.prospera.common.utils.CustomTableNamingStrategy

